language: python
cache: pip
addons:
  postgresql: "10"
python:
  - "3.6"
before_install:
  - sudo apt install make
  - pip install poetry
  - make setuptravis
install:
  - poetry install
script:
  - sudo -u tenark mypy tenark
  - "sudo -u tenark pytest --cov-report term-missing
    --cov-branch --cov tenark tests"
after_success:
  - sudo -u tenark codecov
