language: python
cache: pip
python:
  - "3.6"
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - mypy tenark
  - pytest --cov-report term-missing --cov-branch --cov tenark tests
after_success:
  - codecov
