language: python
cache: pip
addons:
  postgresql: "9.6"
python:
  - "3.8"
before_install:
  - sudo -Hiu postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
  - pip install poetry
install:
  - poetry install
script:
  - mypy tenark
  - pytest --cov-report term-missing --cov-branch --cov tenark tests
after_success:
  - codecov
