language: python
cache: pip
addons:
  postgresql: "9.6"
python:
  - "3.6"
before_install:
  - sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
  - pip install poetry
install:
  - poetry install
script:
  - mypy tenark
  - "sudo -u postgres pytest --cov-report term-missing
    --cov-branch --cov tenark tests"
after_success:
  - codecov
